### ISSUE TITLE
Change default store to `{}`

### ISSUE THREAD

**Issue by jmeas** [cmaher/backbone.hoard#24]
Hoard accomplishes two things right now: single src of truth and local storage data persistence. I think more applications will need the first than the second. I know that I would not choose to use `localStorage` in any app that I've made to date. @cmaher, I believe you mentioned that your app also doesn't use the localStorage feature.

The localStorage adapter should be an additional plugin on top of this library, I think.

**Comment by cmaher** [comment]
:+1:  https://gist.github.com/cmaher/88d7c9c003b6c1d42071 Is a wrapper around a raw object + some size limits to prevent Hoard from running away with memory. Something very similar should be the default store.

**Comment by cmaher** [comment]
resolved by #37
